"""Reads the selection-research surface at ai_videos/_research/.

One dataset per file: `{dataset}.json`, holding a ranked list of candidate
content series plus the real YouTube metrics each ranking claims to rest on.
The reader is read-only — datasets are (re)generated by tools/yt_research.py
plus a research run, never by the webapp.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from libs.infrastructure.errors.research__error import ResearchError

_DATASET = re.compile(r"^[a-z0-9_]+$")


class ResearchReader:
    def __init__(self, repo_root: Path) -> None:
        self.research_root = repo_root / "ai_videos" / "_research"

    def datasets(self) -> list[dict[str, object]]:
        if not self.research_root.is_dir():
            return []
        out: list[dict[str, object]] = []
        for path in sorted(self.research_root.glob("*.json")):
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                continue
            out.append(
                {
                    "dataset": path.stem,
                    "title": data.get("title", path.stem),
                    "generated_at": data.get("generated_at"),
                    "window": data.get("window"),
                    "series_count": len(data.get("series", [])),
                }
            )
        return out

    def _path(self, dataset: str) -> Path:
        if not _DATASET.match(dataset):
            raise ResearchError("bad_name", f"不合法的调研数据集名: {dataset}")
        path = self.research_root / f"{dataset}.json"
        if not path.is_file():
            raise ResearchError("not_found", f"调研数据集不存在: {dataset}")
        return path

    def dataset(self, dataset: str) -> dict[str, object]:
        path = self._path(dataset)
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ResearchError("bad_json", f"{dataset}.json 解析失败: {exc}") from exc
        if not isinstance(data, dict) or not isinstance(data.get("series"), list):
            raise ResearchError("bad_shape", f"{dataset}.json 缺少 series 数组")
        return data

    def series(self, dataset: str, slug: str) -> dict[str, object]:
        for item in self.dataset(dataset)["series"]:  # type: ignore[union-attr]
            if isinstance(item, dict) and item.get("slug") == slug:
                return item
        raise ResearchError("not_found", f"系列不存在: {slug}")
